"""
PortfolioIntelligenceUseCase — Phase 10 Portfolio Intelligence.

Application-layer orchestration for:

    - Portfolio Analytics
    - Portfolio Risk Metrics
    - AI Portfolio Engine
    - Portfolio Optimization
    - AI Recommendations
    - Monte Carlo Simulation

Architecture:

    HTTP/API
        ↓
    Presentation / Dependency Injection
        ↓
    PortfolioIntelligenceUseCase
        ↓
    fetch_holdings_returns()
        ↓
    ┌─────────────────────────────────────────────┐
    │ AnalyticsService                            │
    │ RiskMetricsService                          │
    │ AiPortfolioEngineService                    │
    │ OptimizationService                         │
    │ RecommendationEngineService                 │
    └─────────────────────────────────────────────┘
                       │
                       ▼
             PortfolioIntelligenceResult

Monte Carlo is intentionally exposed through a separate
MonteCarloUseCase because it is independently parameterized
and computationally expensive.

This application layer does not know how ML models are loaded.
AiPortfolioEngineService is injected by the presentation/DI layer.
"""

from __future__ import annotations

from dataclasses import dataclass

from src.application.portfolio_intelligence.ai_portfolio_engine_service import (
    AiPortfolioEngineService,
    AiPortfolioPredictions,
)
from src.application.portfolio_intelligence.analytics_service import (
    AnalyticsService,
    PortfolioAnalytics,
)
from src.application.portfolio_intelligence.data import (
    PortfolioHoldingInput,
    fetch_holdings_returns,
)
from src.application.portfolio_intelligence.monte_carlo_service import (
    MonteCarloResult,
    MonteCarloService,
)
from src.application.portfolio_intelligence.optimization_service import (
    InsufficientHoldingsForOptimizationError,
    OptimizationResult,
    OptimizationService,
)
from src.application.portfolio_intelligence.recommendation_engine_service import (
    Recommendation,
    RecommendationEngineService,
)
from src.application.portfolio_intelligence.risk_metrics_service import (
    RiskMetrics,
    RiskMetricsService,
)
from src.domain.ml.repositories import (
    MarketDataRepository,
    OhlcvBar,
)


# ============================================================================
# PORTFOLIO INTELLIGENCE RESULT
# ============================================================================


@dataclass(frozen=True, slots=True)
class PortfolioIntelligenceResult:
    """
    Complete result of the Phase 10 portfolio-intelligence pipeline.

    Attributes
    ----------
    analytics:
        Historical portfolio analytics and health metrics.

    risk_metrics:
        Portfolio risk measurements.

    ai_predictions:
        Forward-looking AI portfolio predictions generated by the
        existing trained ML infrastructure.

    optimization:
        MPT optimization result.

        None when optimization is not mathematically available,
        for example for a single-holding portfolio.

    recommendations:
        Portfolio-level recommendations generated from the
        complete Phase 10 result.
    """

    analytics: PortfolioAnalytics
    risk_metrics: RiskMetrics
    ai_predictions: AiPortfolioPredictions
    optimization: OptimizationResult | None
    recommendations: tuple[Recommendation, ...]


# ============================================================================
# PORTFOLIO INTELLIGENCE USE CASE
# ============================================================================


class PortfolioIntelligenceUseCase:
    """
    Orchestrates the complete Phase 10 portfolio-intelligence pipeline.

    Flow:

        holdings
            ↓
        fetch_holdings_returns()
            ↓
        shared OHLCV + portfolio returns
            ↓
        AnalyticsService
            ↓
        RiskMetricsService
            ↓
        AiPortfolioEngineService
            ↓
        OptimizationService
            ↓
        RecommendationEngineService
            ↓
        PortfolioIntelligenceResult

    The raw OHLCV bars captured during the initial market-data
    operation are passed to AiPortfolioEngineService so that it
    does not perform a second market-data request.

    AiPortfolioEngineService is intentionally injected into this
    application service. Model-loading concerns belong to the
    presentation/dependency-injection layer.
    """

    def __init__(
        self,
        market_data_repository: MarketDataRepository,
        ai_portfolio_engine_service: AiPortfolioEngineService,
        analytics_service: AnalyticsService | None = None,
        risk_metrics_service: RiskMetricsService | None = None,
        optimization_service: OptimizationService | None = None,
        recommendation_engine_service: RecommendationEngineService | None = None,
    ) -> None:
        """
        Initialize the portfolio-intelligence use case.

        Parameters
        ----------
        market_data_repository:
            Repository used to retrieve market OHLCV data.

        ai_portfolio_engine_service:
            Fully configured AI portfolio engine.

            This dependency is required because the AI portfolio
            engine requires a ModelLoader and must be constructed
            by the presentation/dependency-injection layer.

        analytics_service:
            Optional analytics service. A default implementation
            is created when omitted.

        risk_metrics_service:
            Optional risk metrics service. A default implementation
            is created when omitted.

        optimization_service:
            Optional portfolio optimization service. A default
            implementation is created when omitted.

        recommendation_engine_service:
            Optional recommendation engine. A default implementation
            is created when omitted.
        """

        self._market_data_repository = market_data_repository

        self._ai_portfolio_engine_service = (
            ai_portfolio_engine_service
        )

        self._analytics_service = (
            analytics_service
            if analytics_service is not None
            else AnalyticsService()
        )

        self._risk_metrics_service = (
            risk_metrics_service
            if risk_metrics_service is not None
            else RiskMetricsService()
        )

        self._optimization_service = (
            optimization_service
            if optimization_service is not None
            else OptimizationService()
        )

        self._recommendation_engine_service = (
            recommendation_engine_service
            if recommendation_engine_service is not None
            else RecommendationEngineService()
        )

    async def execute(
        self,
        holdings: list[PortfolioHoldingInput],
        lookback_days: int = 400,
    ) -> PortfolioIntelligenceResult:
        """
        Execute the complete Phase 10 portfolio-intelligence pipeline.

        The market data is fetched once and shared between the
        analytics, risk, AI, optimization, and recommendation
        stages.
        """

        # ------------------------------------------------------------------
        # VALIDATION
        # ------------------------------------------------------------------

        if lookback_days <= 0:
            raise ValueError(
                "lookback_days must be greater than zero."
            )

        if not holdings:
            raise ValueError(
                "At least one portfolio holding is required."
            )

        # ------------------------------------------------------------------
        # SHARED MARKET DATA
        # ------------------------------------------------------------------

        bars_by_symbol: dict[
            str,
            tuple[OhlcvBar, ...],
        ] = {}

        data = await fetch_holdings_returns(
            self._market_data_repository,
            holdings,
            lookback_days,
            bars_out=bars_by_symbol,
        )

        # ------------------------------------------------------------------
        # ANALYTICS
        # ------------------------------------------------------------------

        analytics = self._analytics_service.compute(
            data
        )

        # ------------------------------------------------------------------
        # RISK METRICS
        # ------------------------------------------------------------------

        risk_metrics = self._risk_metrics_service.compute(
            data
        )

        # ------------------------------------------------------------------
        # AI PORTFOLIO ENGINE
        # ------------------------------------------------------------------

        ai_predictions = (
            await self._ai_portfolio_engine_service.compute(
                data=data,
                analytics=analytics,
                risk_metrics=risk_metrics,
                bars_by_symbol=bars_by_symbol,
            )
        )

        # ------------------------------------------------------------------
        # PORTFOLIO OPTIMIZATION
        # ------------------------------------------------------------------

        optimization: OptimizationResult | None

        try:
            optimization = self._optimization_service.optimize(
                data
            )
        except InsufficientHoldingsForOptimizationError:
            optimization = None

        # ------------------------------------------------------------------
        # RECOMMENDATIONS
        # ------------------------------------------------------------------

        recommendations = (
            self._recommendation_engine_service.generate(
                analytics,
                risk_metrics,
                ai_predictions,
                optimization,
            )
        )

        # ------------------------------------------------------------------
        # RESULT
        # ------------------------------------------------------------------

        return PortfolioIntelligenceResult(
            analytics=analytics,
            risk_metrics=risk_metrics,
            ai_predictions=ai_predictions,
            optimization=optimization,
            recommendations=recommendations,
        )


# ============================================================================
# MONTE CARLO USE CASE
# ============================================================================


class MonteCarloUseCase:
    """
    Dedicated application use case for Monte Carlo portfolio simulation.

    Monte Carlo remains separate because:

        - num_runs is request-specific
        - horizon_days is request-specific
        - simulation can be computationally expensive
        - callers may want Monte Carlo without running the complete
          portfolio-intelligence pipeline
        - callers may want portfolio intelligence without Monte Carlo
    """

    def __init__(
        self,
        market_data_repository: MarketDataRepository,
        monte_carlo_service: MonteCarloService | None = None,
    ) -> None:
        """
        Initialize the Monte Carlo use case.
        """

        self._market_data_repository = market_data_repository

        self._monte_carlo_service = (
            monte_carlo_service
            if monte_carlo_service is not None
            else MonteCarloService()
        )

    async def execute(
        self,
        holdings: list[PortfolioHoldingInput],
        num_runs: int,
        horizon_days: int,
        lookback_days: int = 400,
    ) -> MonteCarloResult:
        """
        Execute Monte Carlo portfolio simulation.
        """

        # ------------------------------------------------------------------
        # VALIDATION
        # ------------------------------------------------------------------

        if lookback_days <= 0:
            raise ValueError(
                "lookback_days must be greater than zero."
            )

        if not holdings:
            raise ValueError(
                "At least one portfolio holding is required."
            )

        # ------------------------------------------------------------------
        # MARKET DATA
        # ------------------------------------------------------------------

        data = await fetch_holdings_returns(
            self._market_data_repository,
            holdings,
            lookback_days,
        )

        # ------------------------------------------------------------------
        # MONTE CARLO
        # ------------------------------------------------------------------

        return self._monte_carlo_service.simulate(
            data,
            num_runs=num_runs,
            horizon_days=horizon_days,
        )