"""JWT access token issuance/verification — Document 3 §7.4 (access token,
15 min TTL, contains userId/roles/tokenVersion) and Document 6 §15.4's
revision (kid-based key rotation, overlap window).

Uses PyJWT directly (mature, widely-used library) rather than hand-rolling
JWT encode/decode/signature verification, per the "prefer a mature library"
directive. Refresh tokens are deliberately NOT JWTs (Document 3 §7.4: "Refresh
Token (opaque random string, stored hashed in Postgres...)") — they are
generated by src.infrastructure.security.refresh_token_generator instead.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any
from uuid import uuid4

import jwt

from src.domain.auth.entities import Role
from src.domain.auth.exceptions import InvalidTokenError, TokenExpiredError
from src.domain.auth.value_objects import UserId

ALGORITHM = "HS256"


@dataclass(frozen=True, slots=True)
class AccessTokenClaims:
    user_id: UserId
    role: Role
    token_version: int
    expires_at: datetime
    jti: str
    """Phase 8 addition — a unique id for THIS specific access token,
    distinct from token_version (which invalidates every token for a user
    at once). jti is what TokenBlacklist keys on, letting logout revoke
    exactly the one access token presented, without forcing every other
    active session for that user to re-authenticate too."""


class JwtProvider:
    """kid-based signing (Document 6 §15.4): `current_key` is used for all
    new tokens; `previous_key` (if set) is still accepted for verification
    during a rotation's overlap window, keyed by the `kid` header claim so
    verification knows which key a given token was signed with without
    trial-and-error.
    """

    def __init__(
        self,
        current_kid: str,
        current_secret: str,
        access_token_ttl_minutes: int,
        previous_kid: str | None = None,
        previous_secret: str | None = None,
    ) -> None:
        self._current_kid = current_kid
        self._current_secret = current_secret
        self._access_token_ttl_minutes = access_token_ttl_minutes
        self._previous_kid = previous_kid
        self._previous_secret = previous_secret

    def issue_access_token(self, user_id: UserId, role: Role, token_version: int) -> str:
        now = datetime.now(UTC)
        expires_at = now + timedelta(minutes=self._access_token_ttl_minutes)
        payload: dict[str, Any] = {
            "sub": str(user_id),
            "role": role.value,
            "token_version": token_version,
            "iat": int(now.timestamp()),
            "exp": int(expires_at.timestamp()),
            "jti": str(uuid4()),
        }
        return jwt.encode(
            payload,
            self._current_secret,
            algorithm=ALGORITHM,
            headers={"kid": self._current_kid},
        )

    def verify_access_token(self, token: str) -> AccessTokenClaims:
        try:
            unverified_header = jwt.get_unverified_header(token)
        except jwt.InvalidTokenError as exc:
            raise InvalidTokenError("Malformed token header") from exc

        kid = unverified_header.get("kid")
        secret = self._resolve_secret_for_kid(kid)

        try:
            payload = jwt.decode(token, secret, algorithms=[ALGORITHM])
        except jwt.ExpiredSignatureError as exc:
            raise TokenExpiredError("Access token has expired") from exc
        except jwt.InvalidTokenError as exc:
            raise InvalidTokenError("Invalid access token") from exc

        try:
            return AccessTokenClaims(
                user_id=UserId.from_string(payload["sub"]),
                role=Role(payload["role"]),
                token_version=payload["token_version"],
                expires_at=datetime.fromtimestamp(payload["exp"], tz=UTC),
                # Backward-compatible: a token issued before this Phase 8
                # change has no jti claim at all — rather than hard-failing
                # every outstanding token the moment this ships (forcing an
                # immediate mass logout), such a token is treated as
                # blacklist-unwatchable (it can never be individually
                # revoked by jti, only by the existing token_version bump),
                # which naturally self-resolves as those tokens expire
                # within their normal 15-minute TTL.
                jti=payload.get("jti", ""),
            )
        except (KeyError, ValueError) as exc:
            raise InvalidTokenError("Access token payload is malformed") from exc

    def _resolve_secret_for_kid(self, kid: str | None) -> str:
        if kid == self._current_kid:
            return self._current_secret
        if kid is not None and kid == self._previous_kid and self._previous_secret is not None:
            return self._previous_secret
        raise InvalidTokenError(f"Unknown signing key id: {kid!r}")
