"""
Feature engineering for INVEST IQ.

Responsibilities
----------------

Build the technical-indicator feature matrix used by:

    - Random Forest
    - XGBoost
    - SHAP explainability
    - Decision Engine

The feature pipeline is deliberately deterministic and shared between
training and inference.

Important design rules
----------------------

1. Indicators whose required history is unavailable are omitted.
2. Raw features remain unscaled.
3. Missing indicator warm-up values are handled explicitly.
4. Scaling is performed only when requested by the caller.
5. The latest inference row uses exactly the same feature columns as
   the trained model.
6. No future observations are used to construct a historical feature.
7. Input OHLCV data is validated and sorted chronologically.
8. Feature names are deterministic.
9. Random Forest and XGBoost use binary movement labels:
       1 = future price goes up
       0 = future price stays the same or goes down.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import numpy.typing as npt
import pandas as pd
from sklearn.preprocessing import StandardScaler

from src.infrastructure.ml.features import indicators


# ============================================================================
# CONFIGURATION
# ============================================================================

REQUIRED_OHLCV_COLUMNS: tuple[str, ...] = (
    "open",
    "high",
    "low",
    "close",
    "volume",
)


_INDICATOR_MIN_ROWS: dict[str, int] = {
    "sma_20": 20,
    "sma_50": 50,
    "sma_200": 200,
    "ema_12": 12,
    "ema_26": 26,
    "rsi_14": 14,
    "macd_line": 26,
    "macd_signal": 35,
    "macd_histogram": 35,
    "bb_middle": 20,
    "bb_upper": 20,
    "bb_lower": 20,
    "atr_14": 14,
    "vwap": 1,
    "obv": 1,
    "roc_12": 12,
    "adx_14": 28,
}


# ============================================================================
# FEATURE MATRIX
# ============================================================================


@dataclass(frozen=True, slots=True)
class FeatureMatrix:
    """
    Complete result of feature engineering.

    raw:
        Unscaled technical-indicator features.

    scaled:
        Scaled representation generated by the explicit scale() method.

    included_columns:
        Features actually available for this history length.

    omitted_columns:
        Features excluded because insufficient history existed.
    """

    raw: pd.DataFrame
    scaled: pd.DataFrame
    included_columns: tuple[str, ...]
    omitted_columns: tuple[str, ...]


# ============================================================================
# FEATURE ENGINEER
# ============================================================================


class FeatureEngineer:
    """
    Deterministic technical-indicator feature pipeline.

    The same class must be used during:

        training
        validation
        inference
        SHAP explanation

    This prevents feature-definition drift between model lifecycle stages.
    """

    # ========================================================================
    # BUILD
    # ========================================================================

    def build(
        self,
        ohlcv: pd.DataFrame,
    ) -> FeatureMatrix:
        """
        Build the complete technical-indicator feature matrix.

        Expected input columns:

            open
            high
            low
            close
            volume

        Indicator warm-up NaNs are intentionally preserved here.
        """

        df = self._validate_and_prepare_ohlcv(ohlcv)

        n_rows = len(df)

        candidate_columns: dict[str, pd.Series] = {}

        # --------------------------------------------------------------------
        # MOVING AVERAGES
        # --------------------------------------------------------------------

        if n_rows >= _INDICATOR_MIN_ROWS["sma_20"]:
            candidate_columns["sma_20"] = indicators.sma(
                df["close"],
                20,
            )

        if n_rows >= _INDICATOR_MIN_ROWS["sma_50"]:
            candidate_columns["sma_50"] = indicators.sma(
                df["close"],
                50,
            )

        if n_rows >= _INDICATOR_MIN_ROWS["sma_200"]:
            candidate_columns["sma_200"] = indicators.sma(
                df["close"],
                200,
            )

        # --------------------------------------------------------------------
        # EXPONENTIAL MOVING AVERAGES
        # --------------------------------------------------------------------

        if n_rows >= _INDICATOR_MIN_ROWS["ema_12"]:
            candidate_columns["ema_12"] = indicators.ema(
                df["close"],
                12,
            )

        if n_rows >= _INDICATOR_MIN_ROWS["ema_26"]:
            candidate_columns["ema_26"] = indicators.ema(
                df["close"],
                26,
            )

        # --------------------------------------------------------------------
        # RSI
        # --------------------------------------------------------------------

        if n_rows >= _INDICATOR_MIN_ROWS["rsi_14"]:
            candidate_columns["rsi_14"] = indicators.rsi(
                df["close"],
                14,
            )

        # --------------------------------------------------------------------
        # ATR
        # --------------------------------------------------------------------

        if n_rows >= _INDICATOR_MIN_ROWS["atr_14"]:
            candidate_columns["atr_14"] = indicators.atr(
                df["high"],
                df["low"],
                df["close"],
                14,
            )

        # --------------------------------------------------------------------
        # VWAP
        # --------------------------------------------------------------------

        if n_rows >= _INDICATOR_MIN_ROWS["vwap"]:
            candidate_columns["vwap"] = indicators.vwap(
                df["high"],
                df["low"],
                df["close"],
                df["volume"],
            )

        # --------------------------------------------------------------------
        # OBV
        # --------------------------------------------------------------------

        if n_rows >= _INDICATOR_MIN_ROWS["obv"]:
            candidate_columns["obv"] = indicators.obv(
                df["close"],
                df["volume"],
            )

        # --------------------------------------------------------------------
        # ROC
        # --------------------------------------------------------------------

        if n_rows >= _INDICATOR_MIN_ROWS["roc_12"]:
            candidate_columns["roc_12"] = indicators.roc(
                df["close"],
                12,
            )

        # --------------------------------------------------------------------
        # ADX
        # --------------------------------------------------------------------

        if n_rows >= _INDICATOR_MIN_ROWS["adx_14"]:
            candidate_columns["adx_14"] = indicators.adx(
                df["high"],
                df["low"],
                df["close"],
                14,
            )

        # --------------------------------------------------------------------
        # MACD
        # --------------------------------------------------------------------

        macd_df = indicators.macd(
            df["close"]
        )

        # --------------------------------------------------------------------
        # BOLLINGER BANDS
        # --------------------------------------------------------------------

        bb_df = indicators.bollinger_bands(
            df["close"]
        )

        # --------------------------------------------------------------------
        # ASSEMBLE FEATURES
        # --------------------------------------------------------------------

        feature_frames: list[pd.Series] = []

        included: list[str] = []
        omitted: list[str] = []

        # Candidate scalar indicators.
        for name in (
            "sma_20",
            "sma_50",
            "sma_200",
            "ema_12",
            "ema_26",
            "rsi_14",
            "atr_14",
            "vwap",
            "obv",
            "roc_12",
            "adx_14",
        ):

            minimum_rows = _INDICATOR_MIN_ROWS[name]

            if n_rows >= minimum_rows:

                series = candidate_columns.get(name)

                if series is None:
                    raise RuntimeError(
                        f"Feature '{name}' was expected "
                        "but was not calculated."
                    )

                feature_frames.append(
                    series.rename(name)
                )

                included.append(name)

            else:

                omitted.append(name)

        # --------------------------------------------------------------------
        # MACD
        # --------------------------------------------------------------------

        for name in (
            "macd_line",
            "macd_signal",
            "macd_histogram",
        ):

            minimum_rows = _INDICATOR_MIN_ROWS[name]

            if (
                n_rows >= minimum_rows
                and name in macd_df.columns
            ):

                feature_frames.append(
                    macd_df[name].rename(name)
                )

                included.append(name)

            else:

                omitted.append(name)

        # --------------------------------------------------------------------
        # BOLLINGER BANDS
        # --------------------------------------------------------------------

        for name in (
            "bb_middle",
            "bb_upper",
            "bb_lower",
        ):

            minimum_rows = _INDICATOR_MIN_ROWS[name]

            if (
                n_rows >= minimum_rows
                and name in bb_df.columns
            ):

                feature_frames.append(
                    bb_df[name].rename(name)
                )

                included.append(name)

            else:

                omitted.append(name)

        # --------------------------------------------------------------------
        # RAW MATRIX
        # --------------------------------------------------------------------

        if feature_frames:

            raw = pd.concat(
                feature_frames,
                axis=1,
            )

        else:

            raw = pd.DataFrame(
                index=df.index
            )

        # --------------------------------------------------------------------
        # DUPLICATE FEATURE CHECK
        # --------------------------------------------------------------------

        if not raw.empty:

            duplicate_columns = (
                raw.columns[
                    raw.columns.duplicated()
                ].tolist()
            )

            if duplicate_columns:

                raise RuntimeError(
                    "Feature engineering produced "
                    f"duplicate columns: {duplicate_columns}"
                )

        # --------------------------------------------------------------------
        # SCALED MATRIX
        # --------------------------------------------------------------------

        scaled = self._scale(
            raw
        )

        return FeatureMatrix(
            raw=raw,
            scaled=scaled,
            included_columns=tuple(included),
            omitted_columns=tuple(omitted),
        )

    # ========================================================================
    # OHLCV VALIDATION
    # ========================================================================

    @staticmethod
    def _validate_and_prepare_ohlcv(
        ohlcv: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Validate and normalize OHLCV input.
        """

        if not isinstance(
            ohlcv,
            pd.DataFrame,
        ):

            raise TypeError(
                "ohlcv must be a pandas DataFrame."
            )

        if ohlcv.empty:

            raise ValueError(
                "OHLCV dataframe cannot be empty."
            )

        missing_columns = (
            set(REQUIRED_OHLCV_COLUMNS)
            - set(ohlcv.columns)
        )

        if missing_columns:

            raise ValueError(
                "OHLCV dataframe is missing "
                f"required columns: {sorted(missing_columns)}"
            )

        df = ohlcv[
            list(REQUIRED_OHLCV_COLUMNS)
        ].copy()

        # --------------------------------------------------------------------
        # INDEX
        # --------------------------------------------------------------------

        if not isinstance(
            df.index,
            pd.DatetimeIndex,
        ):

            try:

                df.index = pd.to_datetime(
                    df.index,
                    errors="raise",
                )

            except Exception as exc:

                raise ValueError(
                    "OHLCV index must contain valid "
                    "datetime values."
                ) from exc

        if df.index.tz is not None:

            df.index = (
                df.index
                .tz_convert(None)
            )

        # --------------------------------------------------------------------
        # SORT
        # --------------------------------------------------------------------

        df = df.sort_index()

        # --------------------------------------------------------------------
        # DUPLICATE TIMES
        # --------------------------------------------------------------------

        if df.index.has_duplicates:

            raise ValueError(
                "OHLCV dataframe contains duplicate "
                "bar timestamps."
            )

        # --------------------------------------------------------------------
        # NUMERIC CONVERSION
        # --------------------------------------------------------------------

        for column in (
            "open",
            "high",
            "low",
            "close",
            "volume",
        ):

            df[column] = pd.to_numeric(
                df[column],
                errors="coerce",
            )

        numeric_columns = [
            "open",
            "high",
            "low",
            "close",
            "volume",
        ]

        if df[numeric_columns].isna().any().any():

            raise ValueError(
                "OHLCV dataframe contains "
                "missing or non-numeric values."
            )

        values = df[
            numeric_columns
        ].to_numpy(
            dtype=float
        )

        if not np.isfinite(values).all():

            raise ValueError(
                "OHLCV dataframe contains "
                "NaN or infinite numeric values."
            )

        # --------------------------------------------------------------------
        # PRICE VALIDATION
        # --------------------------------------------------------------------

        if (
            df[
                [
                    "open",
                    "high",
                    "low",
                    "close",
                ]
            ]
            <= 0
        ).any().any():

            raise ValueError(
                "OHLCV prices must be strictly positive."
            )

        # --------------------------------------------------------------------
        # HIGH / LOW VALIDATION
        # --------------------------------------------------------------------

        invalid_high = (
            df["high"]
            < df[
                [
                    "open",
                    "close",
                ]
            ].max(axis=1)
        )

        invalid_low = (
            df["low"]
            > df[
                [
                    "open",
                    "close",
                ]
            ].min(axis=1)
        )

        if invalid_high.any():

            raise ValueError(
                "OHLCV data contains rows where "
                "high is lower than open/close."
            )

        if invalid_low.any():

            raise ValueError(
                "OHLCV data contains rows where "
                "low is higher than open/close."
            )

        # --------------------------------------------------------------------
        # VOLUME
        # --------------------------------------------------------------------

        if (df["volume"] < 0).any():

            raise ValueError(
                "OHLCV volume cannot be negative."
            )

        return df

    # ========================================================================
    # MISSING VALUES
    # ========================================================================

    @staticmethod
    def handle_missing_values(
        df: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Handle indicator warm-up values.

        Only forward filling is performed.

        Back-filling is deliberately forbidden because it can introduce
        future information into historical observations.
        """

        if not isinstance(
            df,
            pd.DataFrame,
        ):

            raise TypeError(
                "df must be a pandas DataFrame."
            )

        if df.empty:

            return df.copy()

        cleaned = (
            df
            .ffill()
            .dropna(
                how="any"
            )
        )

        return cleaned

    # ========================================================================
    # SCALING
    # ========================================================================

    @staticmethod
    def _scale(
        df: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Create a scaled representation of the feature dataframe.

        Random Forest and XGBoost normally consume raw features.
        """

        if (
            df.empty
            or df.shape[1] == 0
        ):

            return df.copy()

        scaled = pd.DataFrame(
            index=df.index,
            columns=df.columns,
            dtype=float,
        )

        for column in df.columns:

            series = pd.to_numeric(
                df[column],
                errors="coerce",
            )

            valid_mask = series.notna()

            if valid_mask.sum() < 2:

                scaled.loc[
                    valid_mask,
                    column,
                ] = series[
                    valid_mask
                ]

                continue

            scaler = StandardScaler()

            values = (
                series[valid_mask]
                .to_numpy(
                    dtype=float
                )
                .reshape(
                    -1,
                    1,
                )
            )

            scaled_values = (
                scaler
                .fit_transform(values)
                .reshape(-1)
            )

            scaled.loc[
                valid_mask,
                column,
            ] = scaled_values

        return scaled

    # ========================================================================
    # PRICE REGRESSION DATASET
    # ========================================================================

    @staticmethod
    def to_supervised_dataset(
        raw_features: pd.DataFrame,
        close: pd.Series,
        horizon_days: int = 1,
    ) -> tuple[
        pd.DataFrame,
        pd.Series,
    ]:
        """
        Construct a chronological PRICE-REGRESSION dataset.

        X:
            Technical features at time t.

        y:
            Future close price at t + horizon_days.

        This method is intended for models that predict an actual
        numerical future price.

        Example:

            X(t) -> 308.26

        It is NOT the method Random Forest/XGBoost should use when those
        models are configured as binary movement classifiers.
        """

        if horizon_days <= 0:

            raise ValueError(
                "horizon_days must be greater than zero."
            )

        if len(raw_features) != len(close):

            raise ValueError(
                "raw_features and close must "
                "have the same number of rows."
            )

        if not raw_features.index.equals(close.index):

            raise ValueError(
                "raw_features and close must "
                "use the same index."
            )

        if raw_features.empty:

            raise ValueError(
                "raw_features cannot be empty."
            )

        close_numeric = pd.to_numeric(
            close,
            errors="coerce",
        )

        if close_numeric.isna().any():

            raise ValueError(
                "close contains missing or "
                "non-numeric values."
            )

        target = (
            close_numeric
            .shift(-horizon_days)
        )

        combined = raw_features.copy()

        combined["_target"] = target

        combined = combined.dropna(
            how="any"
        )

        if combined.empty:

            raise ValueError(
                "No usable supervised-training "
                "rows remain after removing "
                "missing features/targets."
            )

        y = combined.pop(
            "_target"
        )

        X = combined

        return X, y

    # ========================================================================
    # CLASSIFICATION DATASET
    # ========================================================================

    @staticmethod
    def to_classification_dataset(
        raw_features: pd.DataFrame,
        close: pd.Series,
        horizon_days: int = 1,
    ) -> tuple[
        pd.DataFrame,
        pd.Series,
    ]:
        """
        Construct the Random Forest / XGBoost binary classification dataset.

        Label:

            1 -> future close > current close

            0 -> future close <= current close

        The final horizon_days observations are removed because their
        future direction is unavailable.

        Example:

            Today close   = 100
            Tomorrow      = 105
            Label         = 1

            Today close   = 100
            Tomorrow      = 95
            Label         = 0
        """

        if horizon_days <= 0:

            raise ValueError(
                "horizon_days must be greater than zero."
            )

        if len(raw_features) != len(close):

            raise ValueError(
                "raw_features and close must "
                "have the same number of rows."
            )

        if not raw_features.index.equals(close.index):

            raise ValueError(
                "raw_features and close must "
                "use the same index."
            )

        if raw_features.empty:

            raise ValueError(
                "raw_features cannot be empty."
            )

        labels = classification_labels_from_returns(
            close,
            horizon_days,
        )

        combined = raw_features.copy()

        combined["_label"] = labels

        combined = combined.dropna(
            how="any"
        )

        if combined.empty:

            raise ValueError(
                "No usable classification rows "
                "remain after removing missing "
                "features/labels."
            )

        target = (
            combined
            .pop("_label")
            .astype(int)
        )

        features = combined

        return features, target


# ============================================================================
# CLASSIFICATION LABELS
# ============================================================================


def classification_labels_from_returns(
    close: pd.Series,
    horizon_days: int = 1,
) -> pd.Series:
    """
    Create binary future-movement labels.

    1:
        Future price is strictly higher than current price.

    0:
        Future price is equal to or lower than current price.

    NaN:
        Future price does not exist yet.

    No future observation is used to construct the feature values
    themselves. Future data is used ONLY to create the training target.
    """

    if horizon_days <= 0:

        raise ValueError(
            "horizon_days must be greater than zero."
        )

    if not isinstance(
        close,
        pd.Series,
    ):

        raise TypeError(
            "close must be a pandas Series."
        )

    close_numeric = pd.to_numeric(
        close,
        errors="coerce",
    )

    if close_numeric.isna().any():

        raise ValueError(
            "close contains missing or "
            "non-numeric values."
        )

    future = (
        close_numeric
        .shift(-horizon_days)
    )

    labels = pd.Series(
        np.nan,
        index=close.index,
        dtype=float,
    )

    valid = future.notna()

    labels.loc[valid] = (
        future.loc[valid]
        > close_numeric.loc[valid]
    ).astype(int)

    return labels