"""
Domain entities for the AI/ML bounded context.

INVEST IQ Phase 2.

These entities represent:
- model forecasts
- prediction runs
- sentiment results
- recommendations
- trained model versions

ModelVersion is SYMBOL-AWARE.

A trained model is identified by:

    model family + symbol + version

Example:

    random_forest + AAPL + version_1
    random_forest + TSLA + version_1

This prevents the ModelLoader from accidentally loading a model
trained for another stock.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime

from src.domain.ml.value_objects import (
    Confidence,
    DataQuality,
    ExplainabilityPayload,
    ModelFamily,
    ModelVersionId,
    PredictionRunId,
    SentimentLabel,
    Verdict,
)


# ============================================================================
# FORECAST
# ============================================================================


@dataclass(frozen=True, slots=True)
class HorizonPoint:
    """
    A single forecasted price point for a particular prediction horizon.
    """

    horizon_days: int
    predicted_price: float
    lower_bound: float
    upper_bound: float


@dataclass(slots=True)
class Forecast:
    """
    Forecast generated by one model family for one stock symbol.
    """

    id: PredictionRunId
    symbol: str
    model_family: ModelFamily
    model_version_id: ModelVersionId
    points: tuple[HorizonPoint, ...]
    confidence: Confidence
    data_quality: DataQuality
    created_at: datetime

    @classmethod
    def create(
        cls,
        symbol: str,
        model_family: ModelFamily,
        model_version_id: ModelVersionId,
        points: tuple[HorizonPoint, ...],
        confidence: Confidence,
        data_quality: DataQuality,
    ) -> Forecast:

        if not symbol or not symbol.strip():
            raise ValueError("Forecast symbol must not be empty")

        if not points:
            raise ValueError(
                "Forecast must contain at least one HorizonPoint"
            )

        return cls(
            id=PredictionRunId.new(),
            symbol=symbol.upper().strip(),
            model_family=model_family,
            model_version_id=model_version_id,
            points=points,
            confidence=confidence,
            data_quality=data_quality,
            created_at=datetime.now(UTC),
        )

    def point_for_horizon(
        self,
        horizon_days: int,
    ) -> HorizonPoint | None:

        for point in self.points:
            if point.horizon_days == horizon_days:
                return point

        return None


# ============================================================================
# PREDICTION RUN
# ============================================================================


@dataclass(slots=True)
class PredictionRun:
    """
    Immutable record of a completed hybrid prediction.

    A PredictionRun contains all model forecasts that contributed
    to the final ensemble result.
    """

    id: PredictionRunId
    symbol: str
    member_forecasts: tuple[Forecast, ...]
    ensemble_price: float
    ensemble_confidence: Confidence
    data_quality: DataQuality
    explainability: ExplainabilityPayload
    created_at: datetime
    actual_price: float | None = field(default=None)

    @classmethod
    def create(
        cls,
        symbol: str,
        member_forecasts: tuple[Forecast, ...],
        ensemble_price: float,
        ensemble_confidence: Confidence,
        data_quality: DataQuality,
        explainability: ExplainabilityPayload,
    ) -> PredictionRun:

        if not symbol or not symbol.strip():
            raise ValueError(
                "PredictionRun symbol must not be empty"
            )

        if not member_forecasts:
            raise ValueError(
                "PredictionRun requires at least one member Forecast"
            )

        return cls(
            id=PredictionRunId.new(),
            symbol=symbol.upper().strip(),
            member_forecasts=member_forecasts,
            ensemble_price=float(ensemble_price),
            ensemble_confidence=ensemble_confidence,
            data_quality=data_quality,
            explainability=explainability,
            created_at=datetime.now(UTC),
        )

    def record_actual_price(
        self,
        actual_price: float,
    ) -> None:
        """
        Record the actual future market price when available.
        """

        if actual_price <= 0:
            raise ValueError(
                "actual_price must be greater than zero"
            )

        self.actual_price = float(actual_price)

    @property
    def absolute_error(self) -> float | None:

        if self.actual_price is None:
            return None

        return abs(
            self.actual_price - self.ensemble_price
        )


# ============================================================================
# SENTIMENT
# ============================================================================


@dataclass(slots=True)
class SentimentScore:
    """
    FinBERT sentiment result for a text item or aggregated symbol sentiment.
    """

    symbol: str
    label: SentimentLabel
    confidence: Confidence
    article_count: int
    created_at: datetime
    source_text: str | None = field(default=None)

    @classmethod
    def create(
        cls,
        symbol: str,
        label: SentimentLabel,
        confidence: Confidence,
        article_count: int = 1,
        source_text: str | None = None,
    ) -> SentimentScore:

        if not symbol or not symbol.strip():
            raise ValueError(
                "SentimentScore symbol must not be empty"
            )

        if article_count < 1:
            raise ValueError(
                f"article_count must be >= 1, got {article_count}"
            )

        return cls(
            symbol=symbol.upper().strip(),
            label=label,
            confidence=confidence,
            article_count=article_count,
            created_at=datetime.now(UTC),
            source_text=source_text,
        )

    @classmethod
    def aggregate(
        cls,
        symbol: str,
        scores: tuple[SentimentScore, ...],
    ) -> SentimentScore:
        """
        Aggregate multiple FinBERT sentiment scores.
        """

        if not scores:
            raise ValueError(
                "Cannot aggregate an empty tuple of SentimentScore"
            )

        target_volume = 10

        label_weights = {
            "positive": 1.0,
            "neutral": 0.0,
            "negative": -1.0,
        }

        weighted_sum = sum(
            label_weights[score.label]
            * score.confidence.value
            for score in scores
        )

        net_score = weighted_sum / len(scores)

        if net_score > 0.15:
            aggregate_label: SentimentLabel = "positive"

        elif net_score < -0.15:
            aggregate_label = "negative"

        else:
            aggregate_label = "neutral"

        volume_confidence = min(
            1.0,
            len(scores) / target_volume,
        )

        return cls.create(
            symbol=symbol,
            label=aggregate_label,
            confidence=Confidence(
                round(volume_confidence, 4)
            ),
            article_count=len(scores),
        )


# ============================================================================
# RECOMMENDATION
# ============================================================================


@dataclass(slots=True)
class Recommendation:
    """
    Final recommendation generated by the Hybrid Decision Engine.
    """

    id: PredictionRunId
    symbol: str
    verdict: Verdict
    confidence: Confidence
    price_forecast: float
    sentiment_score: float
    explainability: ExplainabilityPayload
    data_quality: DataQuality
    contributing_models: tuple[ModelFamily, ...]
    created_at: datetime

    @classmethod
    def create(
        cls,
        symbol: str,
        verdict: Verdict,
        confidence: Confidence,
        price_forecast: float,
        sentiment_score: float,
        explainability: ExplainabilityPayload,
        data_quality: DataQuality,
        contributing_models: tuple[ModelFamily, ...],
    ) -> Recommendation:

        if not symbol or not symbol.strip():
            raise ValueError(
                "Recommendation symbol must not be empty"
            )

        if not contributing_models:
            raise ValueError(
                "Recommendation requires at least one contributing model"
            )

        if not (
            -1.0
            <= sentiment_score
            <= 1.0
        ):
            raise ValueError(
                "sentiment_score must be in [-1.0, 1.0], "
                f"got {sentiment_score}"
            )

        return cls(
            id=PredictionRunId.new(),
            symbol=symbol.upper().strip(),
            verdict=verdict,
            confidence=confidence,
            price_forecast=float(price_forecast),
            sentiment_score=float(sentiment_score),
            explainability=explainability,
            data_quality=data_quality,
            contributing_models=contributing_models,
            created_at=datetime.now(UTC),
        )


# ============================================================================
# MODEL VERSION
# ============================================================================


ModelStatus = str
"""
Supported lifecycle states:

    training
    validating
    canary
    active
    retired
"""


@dataclass(slots=True)
class ModelVersion:
    """
    Metadata for one trained model artifact.

    IMPORTANT:

    ModelVersion is SYMBOL-AWARE.

    Example:

        family = "lstm"
        symbol = "AAPL"

    is a different model version from:

        family = "lstm"
        symbol = "TSLA"

    This is required because INVEST IQ supports multiple stocks.
    """

    id: ModelVersionId

    # Model family:
    # lstm / arima / prophet / random_forest / xgboost
    family: ModelFamily

    # Stock symbol this model was trained for.
    symbol: str

    # Unique human-readable training version.
    version_tag: str

    # When training completed.
    trained_at: datetime

    # Historical data range used during training.
    training_data_range_start: datetime
    training_data_range_end: datetime

    # Validation metrics produced by the model.
    validation_metrics: dict[str, float]

    # Lifecycle status.
    status: str

    # Path to the trained model artifact.
    artifact_location: str

    # Future canary rollout support.
    rollout_percentage: int = field(default=100)

    @classmethod
    def create(
        cls,
        family: ModelFamily,
        symbol: str,
        version_tag: str,
        training_data_range_start: datetime,
        training_data_range_end: datetime,
        validation_metrics: dict[str, float],
        artifact_location: str,
    ) -> ModelVersion:

        if not symbol or not symbol.strip():
            raise ValueError(
                "ModelVersion symbol must not be empty"
            )

        if not version_tag or not version_tag.strip():
            raise ValueError(
                "ModelVersion version_tag must not be empty"
            )

        if not artifact_location or not artifact_location.strip():
            raise ValueError(
                "ModelVersion artifact_location must not be empty"
            )

        if (
            training_data_range_end
            < training_data_range_start
        ):
            raise ValueError(
                "training_data_range_end cannot be before "
                "training_data_range_start"
            )

        return cls(
            id=ModelVersionId.new(),
            family=family,
            symbol=symbol.upper().strip(),
            version_tag=version_tag,
            trained_at=datetime.now(UTC),
            training_data_range_start=training_data_range_start,
            training_data_range_end=training_data_range_end,
            validation_metrics=validation_metrics,
            status="active",
            artifact_location=artifact_location,
            rollout_percentage=100,
        )

    def retire(self) -> None:
        """
        Retire this model version.
        """

        self.status = "retired"